// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxschrggjvvduphzlvdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4c2NocmdnanZ2ZHVwaHpsdmRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MzU5MjEsImV4cCI6MjA3NTUxMTkyMX0.tS1irbKv1yAnY30rJ8RA5LeR7OdaZPwsP5Q3Ae7Xx8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});